{% set name = "colearn" %}
{% set version = "0.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 394bf7e950c71b14323a2ad24b7670804a3cd79e3578a54a3cb4b7dfbe1e0bd7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - google-cloud-storage ==1.36.1
    - matplotlib ==3.3.4
    - numpy ==1.16.6
    - pandas ==1.2.2
    - pydantic ==1.7.3
    - python ==3.7.5
    - scikit-learn ==0.24.1
    - tensorflow >=2.1.0,<=2.3.0
    - tensorflow-datasets ==1.2.0
    - pytorch ==1.3.1
    - torchvision ==0.4.2
    - pillow ==8.1.0
    - absl-py ==0.11.0
   
  run:
    - google-cloud-storage ==1.36.1
    - matplotlib ==3.3.4
    - numpy ==1.16.6
    - pandas ==1.2.2
    - pydantic ==1.7.3
    - python ==3.7.5
    - scikit-learn ==0.24.1
    - tensorflow >=2.1.0,<=2.3.0
    - tensorflow-datasets ==1.2.0
    - pytorch ==1.3.1
    - torchvision ==0.4.2
    - pillow ==8.1.0
    - absl-py ==0.11.0

test:
  imports:
    - colearn
    - colearn.utils
    - colearn_grpc
    - colearn_keras
    - colearn_other
    - colearn_pytorch

about:
  home: "https://github.com/fetchai/colearn"
  license: Fetch.ai
  license_family:  APACHE
  summary: "The Standalone Fetch AI Collective Learning Framework"

