name: Container Publish
on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    name: Dockerhub Push
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Public Images
        uses: ejfitzgerald/action-docker-tag@v0.2.0
        with:
          repo: fetchai/colearn
          dockerfile: docker/ml.Dockerfile
